sudo: false # force container-based infrastructure
language: node_js
cache:
  directories:
    - tests/elm-stuff/build-artifacts
node_js:
  - "5"
install:
  - npm install -g elm@0.17.0
before_script:
  - cd tests
  - elm package install -y
  - elm make Test.elm --output test.js
script:
  - node test.js
